"""Svaagat Travels — curated luxury hotel collection.

Real, globally renowned luxury properties presented under the Svaagat Travels
premium experience. Room tiers, EDGE loyalty points and enriched detail views
are generated by helpers below to keep this catalogue compact.

Imagery is tasteful, license-friendly luxury-hospitality photography (Unsplash);
it is representative and not the property's official media.
"""

IMG = "https://images.unsplash.com/"

# Shared pool of premium hospitality imagery (exterior, suites, pools, spa, dining)
_GALLERY = {
    "palace": [
        "photo-1566073771259-6a8506099945?w=1200&q=80",
        "photo-1582719478250-c89cae4dc85b?w=1200&q=80",
        "photo-1611892440504-42a792e24d32?w=1200&q=80",
        "photo-1445019980597-93fa8acb246c?w=1200&q=80",
        "photo-1596436889106-be35e843f974?w=1200&q=80",
    ],
    "city": [
        "photo-1551882547-ff40c63fe5fa?w=1200&q=80",
        "photo-1618773928121-c32242e63f39?w=1200&q=80",
        "photo-1590490360182-c33d57733427?w=1200&q=80",
        "photo-1631049307264-da0ec9d70304?w=1200&q=80",
        "photo-1571003123894-1f0594d2b5d9?w=1200&q=80",
    ],
    "resort": [
        "photo-1540541338287-41700207dee6?w=1200&q=80",
        "photo-1584132967334-10e028bd69f7?w=1200&q=80",
        "photo-1602002418082-a4443e081dd1?w=1200&q=80",
        "photo-1578683010236-d716f9a3f461?w=1200&q=80",
        "photo-1520250497591-112f2f40a3f4?w=1200&q=80",
    ],
    "beach": [
        "photo-1544161515-4ab6ce6db874?w=1200&q=80",
        "photo-1573843981267-be1999ff37cd?w=1200&q=80",
        "photo-1512918728675-ed5a9ecdebfd?w=1200&q=80",
        "photo-1439066615861-d1af74d74000?w=1200&q=80",
        "photo-1602002418082-a4443e081dd1?w=1200&q=80",
    ],
}

_AMENITY_SETS = {
    "palace": ["Free Wi-Fi", "Heritage Spa", "Fine Dining", "Airport Transfer", "Outdoor Pool", "Butler Service", "Concierge", "Bar & Lounge"],
    "city": ["Free Wi-Fi", "Rooftop Pool", "Business Centre", "Fitness Studio", "Signature Dining", "Valet Parking", "24x7 Room Service", "Executive Lounge"],
    "resort": ["Free Wi-Fi", "Private Pool", "Wellness Spa", "Multi-cuisine Dining", "Kids Club", "Water Sports", "Yoga Deck", "Beach Access"],
    "beach": ["Free Wi-Fi", "Overwater Villas", "Infinity Pool", "Dive Centre", "Spa Pavilion", "Private Beach", "Sunset Cruise", "Gourmet Dining"],
}


HOTELS = [
    # ---------------- India ----------------
    {
        "id": "htl-taj-mahal-palace-mumbai",
        "name": "The Taj Mahal Palace, Mumbai",
        "city": "Mumbai", "country": "India", "category": "India", "collection": "Heritage",
        "theme": "palace", "star_rating": 5, "price": 24500, "rating": 4.8, "reviews_count": 6421,
        "popular": True, "location": "Apollo Bunder, Colaba",
        "landmark": "Overlooking the Gateway of India & Arabian Sea",
        "tagline": "A living landmark of Indian hospitality since 1903",
        "description": "An iconic Edwardian and Moorish palace on Mumbai's seafront, The Taj Mahal Palace has hosted royalty, statesmen and stars for over a century. Sweeping arches, a legendary central staircase and impeccable service define a stay steeped in grandeur.",
        "tags": ["Heritage", "Sea View", "Iconic"],
    },
    {
        "id": "htl-leela-palace-delhi",
        "name": "The Leela Palace New Delhi",
        "city": "New Delhi", "country": "India", "category": "India", "collection": "Luxury",
        "theme": "palace", "star_rating": 5, "price": 21000, "rating": 4.8, "reviews_count": 4110,
        "popular": True, "location": "Diplomatic Enclave, Chanakyapuri",
        "landmark": "Minutes from India Gate & Lutyens' Delhi",
        "tagline": "Lutyens-inspired palace grandeur in the capital",
        "description": "Inspired by the palaces of Lutyens' Delhi, this address in the Diplomatic Enclave pairs regal interiors with a rooftop pool, award-winning dining and 24-hour butler service — a serene retreat in the heart of the capital.",
        "tags": ["Luxury", "Rooftop Pool", "Business"],
    },
    {
        "id": "htl-rambagh-palace-jaipur",
        "name": "Rambagh Palace, Jaipur",
        "city": "Jaipur", "country": "India", "category": "India", "collection": "Heritage",
        "theme": "palace", "star_rating": 5, "price": 32000, "rating": 4.9, "reviews_count": 3890,
        "popular": True, "location": "Bhawani Singh Road",
        "landmark": "Former residence of the Maharaja of Jaipur",
        "tagline": "The jewel of Jaipur — a former royal residence",
        "description": "Once home to the Maharaja of Jaipur, Rambagh Palace is set within 47 acres of manicured Mughal gardens. Gilded corridors, peacocks on the lawns and candle-lit dinners in the Suvarna Mahal create a truly royal sojourn.",
        "tags": ["Palace", "Royal", "Gardens"],
    },
    {
        "id": "htl-oberoi-udaivilas-udaipur",
        "name": "The Oberoi Udaivilas, Udaipur",
        "city": "Udaipur", "country": "India", "category": "India", "collection": "Luxury",
        "theme": "palace", "star_rating": 5, "price": 38000, "rating": 4.9, "reviews_count": 5210,
        "popular": True, "location": "Haridasji Ki Magri, Lake Pichola",
        "landmark": "On the banks of Lake Pichola",
        "tagline": "Regularly voted among the world's finest hotels",
        "description": "Rising from the shores of Lake Pichola, Udaivilas mirrors the grandeur of a Mewar palace with domed pavilions, reflecting pools and semi-private pool suites. Sunset views across the lake to the City Palace are simply unforgettable.",
        "tags": ["Lake View", "Luxury", "Romantic"],
    },
    {
        "id": "htl-taj-exotica-goa",
        "name": "Taj Exotica Resort & Spa, Goa",
        "city": "Goa", "country": "India", "category": "India", "collection": "Resort",
        "theme": "resort", "star_rating": 5, "price": 18500, "rating": 4.7, "reviews_count": 4732,
        "popular": True, "location": "Benaulim, South Goa",
        "landmark": "56 acres beside Benaulim Beach",
        "tagline": "Mediterranean-style beachfront indulgence",
        "description": "Spread across 56 acres of landscaped gardens beside a quiet stretch of South Goa coast, Taj Exotica blends Mediterranean architecture with tropical calm — lagoon pools, a J Wellness Circle spa and barefoot beach dining.",
        "tags": ["Beach", "Spa", "Family"],
    },
    {
        "id": "htl-lalit-grand-srinagar",
        "name": "The Lalit Grand Palace, Srinagar",
        "city": "Srinagar", "country": "India", "category": "India", "collection": "Heritage",
        "theme": "palace", "star_rating": 5, "price": 16500, "rating": 4.6, "reviews_count": 2140,
        "popular": False, "location": "Gupkar Road, Dal Lake",
        "landmark": "Overlooking Dal Lake & the Zabarwan range",
        "tagline": "A Dogra-era palace amid Himalayan gardens",
        "description": "Built in 1910 as the Maharaja's guest palace, this grand estate sits amid chinar-shaded lawns with sweeping views of Dal Lake and snow-crowned mountains — a heritage haven in the Kashmir Valley.",
        "tags": ["Heritage", "Lake View", "Mountains"],
    },
    {
        "id": "htl-kumarakom-lake-kerala",
        "name": "Kumarakom Lake Resort, Kerala",
        "city": "Kumarakom", "country": "India", "category": "India", "collection": "Resort",
        "theme": "resort", "star_rating": 5, "price": 19500, "rating": 4.8, "reviews_count": 3050,
        "popular": False, "location": "Vembanad Lake, Kottayam",
        "landmark": "On the shores of Vembanad backwaters",
        "tagline": "Meandering pool villas on Kerala's backwaters",
        "description": "A recreation of a traditional Kuttanad village on Vembanad Lake, with heritage villas fronting a meandering pool, an Ayurvedic spa and a floating restaurant serving Keralan cuisine amid swaying palms.",
        "tags": ["Backwaters", "Ayurveda", "Nature"],
    },

    # ---------------- Dubai / UAE ----------------
    {
        "id": "htl-burj-al-arab-dubai",
        "name": "Burj Al Arab Jumeirah, Dubai",
        "city": "Dubai", "country": "United Arab Emirates", "category": "International", "collection": "Luxury",
        "theme": "city", "star_rating": 5, "price": 82000, "rating": 4.9, "reviews_count": 8930,
        "popular": True, "location": "Jumeirah Beach Road",
        "landmark": "The sail-shaped icon of the Dubai skyline",
        "tagline": "The world's most celebrated address",
        "description": "Standing on its own island, the sail-shaped Burj Al Arab is the definitive symbol of Dubai luxury — all duplex suites, a private butler on every floor, gold-leaf interiors and helipad arrivals for the ultimate statement stay.",
        "tags": ["Iconic", "Suites Only", "Beachfront"],
    },
    {
        "id": "htl-atlantis-the-palm-dubai",
        "name": "Atlantis, The Palm, Dubai",
        "city": "Dubai", "country": "United Arab Emirates", "category": "International", "collection": "Resort",
        "theme": "resort", "star_rating": 5, "price": 34000, "rating": 4.7, "reviews_count": 12450,
        "popular": True, "location": "Crescent Road, Palm Jumeirah",
        "landmark": "At the apex of Palm Jumeirah",
        "tagline": "An ocean-themed resort for the whole family",
        "description": "A world unto itself at the tip of Palm Jumeirah — home to the Aquaventure waterpark, The Lost Chambers Aquarium, twenty-plus restaurants and the underwater Neptune & Poseidon suites overlooking the Ambassador Lagoon.",
        "tags": ["Family", "Waterpark", "Beach"],
    },

    # ---------------- Singapore ----------------
    {
        "id": "htl-marina-bay-sands-singapore",
        "name": "Marina Bay Sands, Singapore",
        "city": "Singapore", "country": "Singapore", "category": "International", "collection": "Luxury",
        "theme": "city", "star_rating": 5, "price": 29500, "rating": 4.6, "reviews_count": 15230,
        "popular": True, "location": "Bayfront Avenue",
        "landmark": "Home to the world-famous rooftop infinity pool",
        "tagline": "The skyline-defining SkyPark & infinity edge",
        "description": "Three soaring towers crowned by the legendary 150-metre rooftop infinity pool and SkyPark. At its base lie designer boutiques, celebrity-chef restaurants and a spectacular light-and-water show over Marina Bay.",
        "tags": ["Iconic", "Infinity Pool", "City"],
    },
    {
        "id": "htl-raffles-singapore",
        "name": "Raffles Singapore",
        "city": "Singapore", "country": "Singapore", "category": "International", "collection": "Heritage",
        "theme": "palace", "star_rating": 5, "price": 41000, "rating": 4.8, "reviews_count": 6720,
        "popular": False, "location": "Beach Road, Civic District",
        "landmark": "Colonial landmark & birthplace of the Singapore Sling",
        "tagline": "Colonial grandeur and all-suite elegance",
        "description": "A gleaming-white colonial jewel dating to 1887, Raffles is a sanctuary of all-suite accommodation, tropical courtyards, the storied Long Bar and butler service that has enchanted writers and royalty for generations.",
        "tags": ["Heritage", "Suites Only", "Iconic"],
    },

    # ---------------- Thailand ----------------
    {
        "id": "htl-mandarin-oriental-bangkok",
        "name": "Mandarin Oriental, Bangkok",
        "city": "Bangkok", "country": "Thailand", "category": "International", "collection": "Luxury",
        "theme": "city", "star_rating": 5, "price": 26500, "rating": 4.9, "reviews_count": 5980,
        "popular": True, "location": "Charoen Krung, Riverside",
        "landmark": "On the banks of the Chao Phraya River",
        "tagline": "Legendary riverside service since 1876",
        "description": "One of the world's most awarded hotels, the Mandarin Oriental has graced the Chao Phraya riverside for nearly 150 years — famed for its Authors' Wing, riverside dining and a spa reached by traditional teak boat.",
        "tags": ["Riverside", "Spa", "Iconic"],
    },
    {
        "id": "htl-peninsula-bangkok",
        "name": "The Peninsula Bangkok",
        "city": "Bangkok", "country": "Thailand", "category": "International", "collection": "Luxury",
        "theme": "city", "star_rating": 5, "price": 22000, "rating": 4.8, "reviews_count": 4360,
        "popular": False, "location": "Klongsan, Riverside",
        "landmark": "Panoramic Chao Phraya river frontage",
        "tagline": "River views from every guest room",
        "description": "A striking W-shaped tower designed so every room enjoys sweeping river views. Tropical gardens, a three-tiered riverside pool and a private boat shuttle to the city define effortless Peninsula elegance.",
        "tags": ["River View", "Pool", "Modern"],
    },

    # ---------------- Bali ----------------
    {
        "id": "htl-four-seasons-sayan-bali",
        "name": "Four Seasons Resort Bali at Sayan",
        "city": "Bali", "country": "Indonesia", "category": "International", "collection": "Resort",
        "theme": "resort", "star_rating": 5, "price": 36500, "rating": 4.9, "reviews_count": 3410,
        "popular": True, "location": "Sayan, Ubud",
        "landmark": "Above the Ayung River valley, Ubud",
        "tagline": "A rainforest sanctuary in the heart of Ubud",
        "description": "Approached across a dramatic footbridge into a lotus-pond crowned lobby, this Ubud sanctuary cascades down the Ayung River valley in a tumble of villas and terraced rice paddies — deeply serene and quintessentially Balinese.",
        "tags": ["Jungle", "Wellness", "Romantic"],
    },
    {
        "id": "htl-ritz-carlton-bali",
        "name": "The Ritz-Carlton, Bali",
        "city": "Bali", "country": "Indonesia", "category": "International", "collection": "Resort",
        "theme": "beach", "star_rating": 5, "price": 28500, "rating": 4.8, "reviews_count": 5120,
        "popular": False, "location": "Nusa Dua, Sawangan",
        "landmark": "Clifftop above a white-sand beach",
        "tagline": "Clifftop villas above the Indian Ocean",
        "description": "Set on a dramatic clifftop in Nusa Dua with a private white-sand cove below, the resort offers ocean-front villas with private pools, an aquatic-themed spa and glass-chapel weddings above the surf.",
        "tags": ["Beach", "Cliff View", "Family"],
    },

    # ---------------- Maldives ----------------
    {
        "id": "htl-soneva-fushi-maldives",
        "name": "Soneva Fushi, Maldives",
        "city": "Maldives", "country": "Maldives", "category": "International", "collection": "Beach",
        "theme": "beach", "star_rating": 5, "price": 92000, "rating": 4.9, "reviews_count": 2980,
        "popular": True, "location": "Kunfunadhoo Island, Baa Atoll",
        "landmark": "A private island in a UNESCO Biosphere Reserve",
        "tagline": "Barefoot luxury on a Robinson-Crusoe island",
        "description": "The original barefoot-luxury castaway retreat: sprawling sand-floored villas hidden in dense jungle, an open-air observatory, over-water cinema and 'No News, No Shoes' philosophy on a pristine Baa Atoll island.",
        "tags": ["Private Island", "Overwater", "Eco Luxury"],
    },
    {
        "id": "htl-gili-lankanfushi-maldives",
        "name": "Gili Lankanfushi, Maldives",
        "city": "Maldives", "country": "Maldives", "category": "International", "collection": "Beach",
        "theme": "beach", "star_rating": 5, "price": 78000, "rating": 4.9, "reviews_count": 2410,
        "popular": False, "location": "Lankanfushi Island, North Malé Atoll",
        "landmark": "Overwater villas reached by boat",
        "tagline": "Rustic-chic overwater villas & a Mr/Mrs Friday butler",
        "description": "Crusoe-esque overwater residences crafted from sustainable timber, each with a personal 'Mr or Mrs Friday' butler, a rooftop sundeck and a private overwater hammock — the last word in laid-back Maldivian romance.",
        "tags": ["Overwater", "Romantic", "Butler"],
    },

    # ---------------- Europe ----------------
    {
        "id": "htl-ritz-paris",
        "name": "Ritz Paris",
        "city": "Paris", "country": "France", "category": "International", "collection": "Luxury",
        "theme": "palace", "star_rating": 5, "price": 96000, "rating": 4.9, "reviews_count": 3620,
        "popular": True, "location": "15 Place Vendôme",
        "landmark": "On the elegant Place Vendôme",
        "tagline": "The palace that gave 'ritzy' its meaning",
        "description": "Since 1898 the Ritz has been the very definition of Parisian glamour — gilded salons, the Bar Hemingway, a subterranean Chanel spa and haute-couture suites overlooking the Place Vendôme.",
        "tags": ["Palace", "Iconic", "Couture"],
    },
    {
        "id": "htl-savoy-london",
        "name": "The Savoy, London",
        "city": "London", "country": "United Kingdom", "category": "International", "collection": "Heritage",
        "theme": "palace", "star_rating": 5, "price": 71000, "rating": 4.8, "reviews_count": 5240,
        "popular": True, "location": "Strand, Covent Garden",
        "landmark": "Overlooking the River Thames",
        "tagline": "Art-Deco glamour on the Strand since 1889",
        "description": "A London legend blending Edwardian and Art-Deco splendour — home to the American Bar, afternoon tea in the Thames Foyer and river-view suites moments from Covent Garden and the West End.",
        "tags": ["Heritage", "River View", "Iconic"],
    },
]


# -------- Room tier generation (Deluxe / Club / Suite) --------
ROOM_TIERS = [
    {
        "name": "Deluxe Room", "mult": 1.00, "size": "42 sq.m.", "occupancy": "2 Adults",
        "bed": "King or Twin",
        "perks": ["Complimentary breakfast", "Free high-speed Wi-Fi", "Daily housekeeping", "In-room tea & coffee"],
    },
    {
        "name": "Club Room", "mult": 1.35, "size": "58 sq.m.", "occupancy": "2 Adults + 1 Child",
        "bed": "King",
        "perks": ["Executive Lounge access", "Complimentary breakfast & evening cocktails", "Premium city/garden view", "Late checkout on request"],
    },
    {
        "name": "Luxury Suite", "mult": 1.95, "size": "95 sq.m.", "occupancy": "3 Adults",
        "bed": "King + Living Room",
        "perks": ["Personal butler service", "Private lounge & bar access", "Signature suite amenities", "Airport transfer included", "Priority spa reservations"],
    },
]


def _round_price(v: float) -> int:
    return int(round(v / 100.0) * 100)


def hotel_room_types(base_price: float):
    tiers = []
    for t in ROOM_TIERS:
        price = _round_price(base_price * t["mult"])
        tiers.append({
            "name": t["name"],
            "price": price,
            "size": t["size"],
            "occupancy": t["occupancy"],
            "bed": t["bed"],
            "perks": t["perks"],
            "edge_points": price // 100,
        })
    return tiers


def hotel_list_item(h: dict) -> dict:
    """Compact card payload."""
    gallery = _GALLERY.get(h["theme"], _GALLERY["city"])
    return {
        "id": h["id"],
        "name": h["name"],
        "city": h["city"],
        "country": h["country"],
        "category": h["category"],
        "collection": h["collection"],
        "star_rating": h["star_rating"],
        "price": h["price"],
        "rating": h["rating"],
        "reviews_count": h["reviews_count"],
        "popular": h.get("popular", False),
        "location": h["location"],
        "landmark": h["landmark"],
        "tagline": h["tagline"],
        "tags": h["tags"],
        "image": IMG + gallery[0],
    }


def hotel_detail(h: dict) -> dict:
    gallery = _GALLERY.get(h["theme"], _GALLERY["city"])
    amenities = _AMENITY_SETS.get(h["theme"], _AMENITY_SETS["city"])
    item = hotel_list_item(h)
    item.update({
        "description": h["description"],
        "images": [IMG + g for g in gallery],
        "amenities": amenities,
        "room_types": hotel_room_types(h["price"]),
        "highlights": [
            h["landmark"],
            f"{h['star_rating']}-star {h['collection'].lower()} experience",
            "EDGE loyalty points on every booking",
            "24x7 concierge & dedicated Svaagat travel desk",
        ],
        "policies": {
            "check_in": "2:00 PM", "check_out": "12:00 PM",
            "cancellation": "Free cancellation up to 48 hours before check-in",
            "children": "Children of all ages welcome",
        },
    })
    return item


def get_hotel(hotel_id: str):
    for h in HOTELS:
        if h["id"] == hotel_id:
            return h
    return None


def hotel_destinations():
    """City groupings for the homepage 'Explore Hotel Stays' section."""
    city_images = {
        "Mumbai": "photo-1529253355930-ddbe423a2ac7?w=800&q=80",
        "New Delhi": "photo-1587474260584-136574528ed5?w=800&q=80",
        "Jaipur": "photo-1477587458883-47145ed94245?w=800&q=80",
        "Udaipur": "photo-1615836245337-f5b9b2303f10?w=800&q=80",
        "Goa": "photo-1512343879784-a960bf40e7f2?w=800&q=80",
        "Srinagar": "photo-1609920658906-8223bd289001?w=800&q=80",
        "Kumarakom": "photo-1602216056096-3b40cc0c9944?w=800&q=80",
        "Dubai": "photo-1512453979798-5ea266f8880c?w=800&q=80",
        "Singapore": "photo-1525625293386-3f8f99389edd?w=800&q=80",
        "Bangkok": "photo-1563492065599-3520f775eeed?w=800&q=80",
        "Bali": "photo-1537996194471-e657df975ab4?w=800&q=80",
        "Maldives": "photo-1514282401047-d79a71a590e8?w=800&q=80",
        "Paris": "photo-1502602898657-3e91760cbb34?w=800&q=80",
        "London": "photo-1513635269975-59663e0ac1ad?w=800&q=80",
    }
    order = []
    grouped = {}
    for h in HOTELS:
        city = h["city"]
        if city not in grouped:
            img = city_images.get(city, _GALLERY.get(h["theme"], _GALLERY["city"])[0])
            grouped[city] = {
                "city": city,
                "country": h["country"],
                "count": 0,
                "image": IMG + img,
                "from_price": h["price"],
            }
            order.append(city)
        grouped[city]["count"] += 1
        grouped[city]["from_price"] = min(grouped[city]["from_price"], h["price"])
    return [grouped[c] for c in order]
