"""Svaagat Travels seed content. No live/third-party data — static curated content."""

IMG = "https://images.unsplash.com/"

PACKAGES = [
    {
        "id": "pkg-dubai-delight",
        "title": "Dubai Delight with Desert Safari",
        "destination": "Dubai",
        "country": "United Arab Emirates",
        "category": "International",
        "region": "Middle East",
        "price": 54999,
        "duration_nights": 4,
        "duration_days": 5,
        "image": IMG + "photo-1512453979798-5ea266f8880c?w=1200&q=80",
        "rating": 4.7,
        "reviews_count": 1284,
        "popular": True,
        "best_time": "Oct - Mar",
        "description": "Experience the dazzling city of Dubai with iconic skyscrapers, a thrilling desert safari, and world-class shopping. A perfect blend of modern luxury and Arabian charm.",
        "highlights": ["Burj Khalifa 124th floor entry", "Desert Safari with BBQ dinner", "Dhow Cruise at Dubai Marina", "Dubai Mall & Fountain show", "Half-day city tour"],
        "inclusions": ["4 nights hotel stay", "Daily breakfast", "Airport transfers", "Return economy airfare", "Visa assistance", "Tour manager"],
        "tags": ["Family", "Adventure", "Shopping"],
        "itinerary": [
            {"day": 1, "title": "Arrival in Dubai", "detail": "Arrive at Dubai International Airport, transfer to hotel, evening at leisure."},
            {"day": 2, "title": "City Tour & Desert Safari", "detail": "Half-day city tour followed by an exhilarating desert safari with BBQ dinner."},
            {"day": 3, "title": "Burj Khalifa & Dubai Mall", "detail": "Visit the world's tallest building and enjoy the Dubai Fountain show."},
            {"day": 4, "title": "Dhow Cruise", "detail": "Free morning for shopping; evening Dhow cruise dinner at Marina."},
            {"day": 5, "title": "Departure", "detail": "Transfer to airport for your return flight."},
        ],
    },
    {
        "id": "pkg-thailand-explorer",
        "title": "Thailand Explorer - Bangkok & Pattaya",
        "destination": "Bangkok",
        "country": "Thailand",
        "category": "International",
        "region": "South East Asia",
        "price": 39999,
        "duration_nights": 5,
        "duration_days": 6,
        "image": IMG + "photo-1552465011-b4e21bf6e79a?w=1200&q=80",
        "rating": 4.5,
        "reviews_count": 2103,
        "popular": True,
        "best_time": "Nov - Feb",
        "description": "Discover the vibrant energy of Bangkok and the sun-kissed beaches of Pattaya. Temples, floating markets, island tours and buzzing nightlife await.",
        "highlights": ["Coral Island tour", "Alcazar Show", "Safari World & Marine Park", "Floating market visit", "Gems gallery tour"],
        "inclusions": ["5 nights hotel stay", "Daily breakfast", "Airport transfers", "Return economy airfare", "Visa on arrival assistance", "English speaking guide"],
        "tags": ["Beach", "Nightlife", "Couples"],
        "itinerary": [
            {"day": 1, "title": "Arrive Pattaya", "detail": "Arrive Bangkok, transfer to Pattaya, evening free."},
            {"day": 2, "title": "Coral Island", "detail": "Speedboat to Coral Island with water sports options."},
            {"day": 3, "title": "Pattaya to Bangkok", "detail": "Alcazar show, transfer to Bangkok."},
            {"day": 4, "title": "Safari World", "detail": "Full day at Safari World & Marine Park."},
            {"day": 5, "title": "Bangkok City", "detail": "City & temple tour with shopping."},
            {"day": 6, "title": "Departure", "detail": "Transfer to airport for departure."},
        ],
    },
    {
        "id": "pkg-bali-romance",
        "title": "Bali Romance Getaway",
        "destination": "Bali",
        "country": "Indonesia",
        "category": "International",
        "region": "South East Asia",
        "price": 62999,
        "duration_nights": 6,
        "duration_days": 7,
        "image": IMG + "photo-1537996194471-e657df975ab4?w=1200&q=80",
        "rating": 4.8,
        "reviews_count": 1567,
        "popular": True,
        "best_time": "Apr - Oct",
        "description": "A dreamy island escape featuring lush rice terraces, sacred temples, pristine beaches and unforgettable sunsets. Ideal for honeymooners.",
        "highlights": ["Ubud rice terraces", "Uluwatu Temple sunset", "Nusa Penida island tour", "Kintamani volcano view", "Romantic candlelight dinner"],
        "inclusions": ["6 nights hotel stay", "Daily breakfast", "Private transfers", "Return economy airfare", "Honeymoon inclusions", "Local guide"],
        "tags": ["Honeymoon", "Beach", "Nature"],
        "itinerary": [
            {"day": 1, "title": "Arrive Bali", "detail": "Arrival and transfer to resort in Kuta."},
            {"day": 2, "title": "Ubud Tour", "detail": "Rice terraces, monkey forest and art villages."},
            {"day": 3, "title": "Nusa Penida", "detail": "Full day island hopping tour."},
            {"day": 4, "title": "Kintamani", "detail": "Volcano views and hot springs."},
            {"day": 5, "title": "Uluwatu", "detail": "Temple visit and Kecak fire dance at sunset."},
            {"day": 6, "title": "Leisure", "detail": "Free day at beach or spa."},
            {"day": 7, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-maldives-luxury",
        "title": "Maldives Luxury Water Villa Escape",
        "destination": "Maldives",
        "country": "Maldives",
        "category": "International",
        "region": "Indian Ocean",
        "price": 89999,
        "duration_nights": 3,
        "duration_days": 4,
        "image": IMG + "photo-1514282401047-d79a71a590e8?w=1200&q=80",
        "rating": 4.9,
        "reviews_count": 892,
        "popular": True,
        "best_time": "Nov - Apr",
        "description": "Wake up over turquoise lagoons in an overwater villa. Snorkel vibrant reefs, indulge in spa rituals and dine under the stars.",
        "highlights": ["Overwater villa stay", "Snorkeling & reef tour", "Sunset dolphin cruise", "Spa session", "Speedboat transfers"],
        "inclusions": ["3 nights water villa", "All meals (Full board)", "Speedboat/seaplane transfers", "Return economy airfare", "Snorkeling gear"],
        "tags": ["Luxury", "Honeymoon", "Beach"],
        "itinerary": [
            {"day": 1, "title": "Arrival", "detail": "Seaplane transfer to resort, check-in to water villa."},
            {"day": 2, "title": "Reef & Relax", "detail": "Snorkeling tour and spa in the afternoon."},
            {"day": 3, "title": "Dolphin Cruise", "detail": "Sunset dolphin cruise and beach dinner."},
            {"day": 4, "title": "Departure", "detail": "Transfer to Male for departure."},
        ],
    },
    {
        "id": "pkg-singapore-family",
        "title": "Singapore Family Fun",
        "destination": "Singapore",
        "country": "Singapore",
        "category": "International",
        "region": "South East Asia",
        "price": 58999,
        "duration_nights": 4,
        "duration_days": 5,
        "image": IMG + "photo-1525625293386-3f8f99389edd?w=1200&q=80",
        "rating": 4.6,
        "reviews_count": 1745,
        "popular": False,
        "best_time": "All year",
        "description": "A clean, green and thrilling city-state packed with family attractions - from Universal Studios to Gardens by the Bay.",
        "highlights": ["Universal Studios Sentosa", "Gardens by the Bay", "Marina Bay Sands SkyPark", "Night Safari", "City & Sentosa tour"],
        "inclusions": ["4 nights hotel stay", "Daily breakfast", "Airport transfers", "Return economy airfare", "Attraction tickets"],
        "tags": ["Family", "City", "Kids"],
        "itinerary": [
            {"day": 1, "title": "Arrival", "detail": "Arrive Singapore, transfer to hotel."},
            {"day": 2, "title": "City Tour", "detail": "Half-day city tour and Gardens by the Bay."},
            {"day": 3, "title": "Sentosa", "detail": "Full day at Universal Studios."},
            {"day": 4, "title": "Night Safari", "detail": "Free day with evening Night Safari."},
            {"day": 5, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-europe-highlights",
        "title": "Best of Europe - 4 Countries",
        "destination": "Paris",
        "country": "France, Switzerland, Italy, Netherlands",
        "category": "International",
        "region": "Europe",
        "price": 189999,
        "duration_nights": 9,
        "duration_days": 10,
        "image": IMG + "photo-1502602898657-3e91760cbb34?w=1200&q=80",
        "rating": 4.7,
        "reviews_count": 634,
        "popular": True,
        "best_time": "May - Sep",
        "description": "A grand European tour covering Paris, the Swiss Alps, Venice, Rome and Amsterdam. Iconic landmarks, scenic train rides and rich culture.",
        "highlights": ["Eiffel Tower & Seine cruise", "Mt. Titlis excursion", "Venice gondola experience", "Vatican & Colosseum", "Amsterdam canal cruise"],
        "inclusions": ["9 nights hotel stay", "Daily breakfast & Indian dinner", "Coach transfers", "Return economy airfare", "Schengen visa assistance", "Tour manager"],
        "tags": ["Culture", "Sightseeing", "Family"],
        "itinerary": [
            {"day": 1, "title": "Arrive Paris", "detail": "Arrival and transfer to hotel."},
            {"day": 2, "title": "Paris", "detail": "Eiffel Tower, city tour and Seine cruise."},
            {"day": 3, "title": "Paris to Switzerland", "detail": "Travel to Swiss Alps region."},
            {"day": 4, "title": "Mt. Titlis", "detail": "Cable car excursion to snow-capped peaks."},
            {"day": 5, "title": "Switzerland to Venice", "detail": "Scenic drive to Italy."},
            {"day": 6, "title": "Venice", "detail": "Gondola ride and St. Mark's Square."},
            {"day": 7, "title": "Rome", "detail": "Vatican City and Colosseum tour."},
            {"day": 8, "title": "Rome to Amsterdam", "detail": "Fly to Amsterdam."},
            {"day": 9, "title": "Amsterdam", "detail": "Canal cruise and city tour."},
            {"day": 10, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-vietnam-discovery",
        "title": "Vietnam Discovery",
        "destination": "Hanoi",
        "country": "Vietnam",
        "category": "International",
        "region": "South East Asia",
        "price": 64999,
        "duration_nights": 6,
        "duration_days": 7,
        "image": IMG + "photo-1528127269322-539801943592?w=1200&q=80",
        "rating": 4.5,
        "reviews_count": 512,
        "popular": False,
        "best_time": "Oct - Apr",
        "description": "From the emerald waters of Ha Long Bay to bustling Ho Chi Minh City, discover Vietnam's stunning landscapes and rich heritage.",
        "highlights": ["Ha Long Bay overnight cruise", "Cu Chi Tunnels", "Hanoi Old Quarter", "Mekong Delta tour", "Water puppet show"],
        "inclusions": ["6 nights stay incl. cruise", "Daily breakfast", "Transfers", "Return economy airfare", "Guided tours"],
        "tags": ["Culture", "Nature", "Adventure"],
        "itinerary": [
            {"day": 1, "title": "Arrive Hanoi", "detail": "Arrival and city orientation."},
            {"day": 2, "title": "Ha Long Bay", "detail": "Overnight cruise on the bay."},
            {"day": 3, "title": "Return Hanoi", "detail": "Cruise activities and return."},
            {"day": 4, "title": "Fly to HCMC", "detail": "Transfer to Ho Chi Minh City."},
            {"day": 5, "title": "Cu Chi Tunnels", "detail": "Historical tunnels tour."},
            {"day": 6, "title": "Mekong Delta", "detail": "Boat tour and local villages."},
            {"day": 7, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-kashmir-paradise",
        "title": "Kashmir Paradise on Earth",
        "destination": "Srinagar",
        "country": "India",
        "category": "India",
        "region": "North India",
        "price": 28999,
        "duration_nights": 5,
        "duration_days": 6,
        "image": IMG + "photo-1605649487212-47bdab064df7?w=1200&q=80",
        "rating": 4.6,
        "reviews_count": 2890,
        "popular": True,
        "best_time": "Mar - Oct",
        "description": "Experience the breathtaking beauty of Kashmir - shimmering Dal Lake, snow-clad Gulmarg, blooming Pahalgam valleys and cosy houseboats.",
        "highlights": ["Shikara ride on Dal Lake", "Gulmarg Gondola", "Betaab Valley Pahalgam", "Mughal Gardens", "Houseboat stay"],
        "inclusions": ["4 nights hotel + 1 houseboat", "Breakfast & dinner", "All transfers by car", "Sightseeing", "Driver allowance"],
        "tags": ["Nature", "Honeymoon", "Mountains"],
        "itinerary": [
            {"day": 1, "title": "Arrive Srinagar", "detail": "Shikara ride and houseboat check-in."},
            {"day": 2, "title": "Gulmarg", "detail": "Gondola ride at meadow of flowers."},
            {"day": 3, "title": "Pahalgam", "detail": "Betaab and Aru valleys."},
            {"day": 4, "title": "Sonamarg", "detail": "Day excursion to golden meadow."},
            {"day": 5, "title": "Srinagar", "detail": "Mughal Gardens and local markets."},
            {"day": 6, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-kerala-backwaters",
        "title": "Kerala Backwaters & Hills",
        "destination": "Munnar",
        "country": "India",
        "category": "India",
        "region": "South India",
        "price": 24999,
        "duration_nights": 5,
        "duration_days": 6,
        "image": IMG + "photo-1602216056096-3b40cc0c9944?w=1200&q=80",
        "rating": 4.7,
        "reviews_count": 3120,
        "popular": True,
        "best_time": "Sep - Mar",
        "description": "God's Own Country - misty tea gardens of Munnar, wildlife at Thekkady and a serene houseboat cruise through Alleppey backwaters.",
        "highlights": ["Munnar tea gardens", "Thekkady spice plantation", "Alleppey houseboat cruise", "Kathakali performance", "Ayurvedic spa"],
        "inclusions": ["4 nights hotel + 1 houseboat", "Breakfast & dinner", "AC vehicle transfers", "Sightseeing", "Houseboat full board"],
        "tags": ["Nature", "Honeymoon", "Relaxation"],
        "itinerary": [
            {"day": 1, "title": "Arrive Cochin", "detail": "Transfer to Munnar."},
            {"day": 2, "title": "Munnar", "detail": "Tea gardens and Eravikulam park."},
            {"day": 3, "title": "Thekkady", "detail": "Periyar wildlife and spice tour."},
            {"day": 4, "title": "Alleppey", "detail": "Houseboat cruise on backwaters."},
            {"day": 5, "title": "Cochin", "detail": "Fort Kochi city tour."},
            {"day": 6, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-andaman-islands",
        "title": "Andaman Island Hopping",
        "destination": "Port Blair",
        "country": "India",
        "category": "India",
        "region": "Islands",
        "price": 34999,
        "duration_nights": 5,
        "duration_days": 6,
        "image": IMG + "photo-1589979481223-deb893043163?w=1200&q=80",
        "rating": 4.6,
        "reviews_count": 1456,
        "popular": False,
        "best_time": "Oct - May",
        "description": "Crystal clear waters, coral reefs and pristine white beaches. Explore Havelock, Neil Island and the historic Cellular Jail.",
        "highlights": ["Radhanagar Beach", "Scuba diving at Havelock", "Cellular Jail light & sound show", "Neil Island tour", "Ross Island visit"],
        "inclusions": ["5 nights hotel stay", "Daily breakfast", "Ferry & transfers", "Sightseeing", "Permits"],
        "tags": ["Beach", "Adventure", "Family"],
        "itinerary": [
            {"day": 1, "title": "Arrive Port Blair", "detail": "Cellular Jail and light show."},
            {"day": 2, "title": "Havelock", "detail": "Ferry to Havelock, Radhanagar beach."},
            {"day": 3, "title": "Havelock", "detail": "Scuba/snorkeling activities."},
            {"day": 4, "title": "Neil Island", "detail": "Natural bridge and beaches."},
            {"day": 5, "title": "Port Blair", "detail": "Ross Island and shopping."},
            {"day": 6, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-ladakh-adventure",
        "title": "Leh Ladakh Adventure",
        "destination": "Leh",
        "country": "India",
        "category": "India",
        "region": "North India",
        "price": 32999,
        "duration_nights": 6,
        "duration_days": 7,
        "image": IMG + "photo-1581791534721-e599df4417f7?w=1200&q=80",
        "rating": 4.8,
        "reviews_count": 987,
        "popular": False,
        "best_time": "May - Sep",
        "description": "A high-altitude adventure through dramatic mountainscapes, ancient monasteries, Pangong Lake and the world's highest motorable passes.",
        "highlights": ["Pangong Lake", "Nubra Valley & camel safari", "Khardung La pass", "Monastery tours", "Magnetic Hill"],
        "inclusions": ["6 nights stay", "Breakfast & dinner", "Inner line permits", "SUV transfers", "Oxygen support"],
        "tags": ["Adventure", "Mountains", "Roadtrip"],
        "itinerary": [
            {"day": 1, "title": "Arrive Leh", "detail": "Acclimatization day."},
            {"day": 2, "title": "Leh Local", "detail": "Monasteries and Shanti Stupa."},
            {"day": 3, "title": "Nubra Valley", "detail": "Khardung La and camel safari."},
            {"day": 4, "title": "Pangong Lake", "detail": "Drive to the famous blue lake."},
            {"day": 5, "title": "Return Leh", "detail": "Via Chang La pass."},
            {"day": 6, "title": "Leh", "detail": "Magnetic hill and Gurudwara."},
            {"day": 7, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-goa-beach",
        "title": "Goa Beach Holiday",
        "destination": "Goa",
        "country": "India",
        "category": "India",
        "region": "Beaches",
        "price": 18999,
        "duration_nights": 3,
        "duration_days": 4,
        "image": IMG + "photo-1512343879784-a960bf40e7f2?w=1200&q=80",
        "rating": 4.4,
        "reviews_count": 4231,
        "popular": True,
        "best_time": "Nov - Feb",
        "description": "Sun, sand and sea! Enjoy the golden beaches of Goa, vibrant nightlife, water sports and Portuguese heritage.",
        "highlights": ["North & South Goa tour", "Water sports at Baga", "Sunset cruise", "Old Goa churches", "Beach shacks & nightlife"],
        "inclusions": ["3 nights hotel stay", "Daily breakfast", "Airport transfers", "North Goa sightseeing"],
        "tags": ["Beach", "Nightlife", "Couples"],
        "itinerary": [
            {"day": 1, "title": "Arrive Goa", "detail": "Transfer to hotel, evening at beach."},
            {"day": 2, "title": "North Goa", "detail": "Calangute, Baga, Fort Aguada."},
            {"day": 3, "title": "South Goa", "detail": "Churches, spice plantation, cruise."},
            {"day": 4, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-australia-discovery",
        "title": "Australia Discovery - Sydney & Gold Coast",
        "destination": "Sydney",
        "country": "Australia",
        "category": "International",
        "region": "Oceania",
        "price": 149999,
        "duration_nights": 7,
        "duration_days": 8,
        "image": IMG + "photo-1506973035872-a4ec16b8e8d9?w=1200&q=80",
        "rating": 4.7,
        "reviews_count": 742,
        "popular": False,
        "best_time": "Sep - Nov",
        "description": "From the iconic Sydney Opera House to the golden beaches of the Gold Coast, experience the very best of Australia's cities, coastline and wildlife.",
        "highlights": ["Sydney Opera House & Harbour cruise", "Bondi Beach visit", "Gold Coast theme parks", "Currumbin Wildlife Sanctuary", "Blue Mountains day trip"],
        "inclusions": ["7 nights hotel stay", "Daily breakfast", "Airport transfers", "Return economy airfare", "Visa assistance", "City tours"],
        "tags": ["Family", "Beach", "Adventure"],
        "itinerary": [
            {"day": 1, "title": "Arrive Sydney", "detail": "Arrival and transfer to hotel."},
            {"day": 2, "title": "Sydney City", "detail": "Opera House, Harbour Bridge and cruise."},
            {"day": 3, "title": "Blue Mountains", "detail": "Day trip with scenic railway."},
            {"day": 4, "title": "Fly to Gold Coast", "detail": "Transfer and beach evening."},
            {"day": 5, "title": "Theme Parks", "detail": "Full day at Movie World / Sea World."},
            {"day": 6, "title": "Wildlife", "detail": "Currumbin Wildlife Sanctuary."},
            {"day": 7, "title": "Leisure", "detail": "Free day for shopping or surfing."},
            {"day": 8, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-japan-highlights",
        "title": "Japan Highlights - Tokyo, Kyoto & Osaka",
        "destination": "Tokyo",
        "country": "Japan",
        "category": "International",
        "region": "East Asia",
        "price": 179999,
        "duration_nights": 7,
        "duration_days": 8,
        "image": IMG + "photo-1493976040374-85c8e12f0c0e?w=1200&q=80",
        "rating": 4.9,
        "reviews_count": 968,
        "popular": True,
        "best_time": "Mar - May & Oct - Nov",
        "description": "Discover the perfect blend of ancient tradition and futuristic wonder - from Tokyo's neon streets to Kyoto's serene temples and Mt. Fuji's majesty.",
        "highlights": ["Mt. Fuji & Hakone excursion", "Tokyo city & Shibuya", "Kyoto golden pavilion", "Osaka Castle & Dotonbori", "Bullet train (Shinkansen) ride"],
        "inclusions": ["7 nights hotel stay", "Daily breakfast", "JR bullet train pass", "Return economy airfare", "Visa assistance", "English guide"],
        "tags": ["Culture", "Family", "Sightseeing"],
        "itinerary": [
            {"day": 1, "title": "Arrive Tokyo", "detail": "Arrival and transfer to hotel."},
            {"day": 2, "title": "Tokyo City", "detail": "Asakusa, Shibuya and Tokyo Tower."},
            {"day": 3, "title": "Mt. Fuji", "detail": "Hakone and Lake Ashi cruise."},
            {"day": 4, "title": "To Kyoto", "detail": "Bullet train to Kyoto."},
            {"day": 5, "title": "Kyoto", "detail": "Golden Pavilion and Fushimi Inari."},
            {"day": 6, "title": "Osaka", "detail": "Osaka Castle and Dotonbori."},
            {"day": 7, "title": "Leisure", "detail": "Free day / Universal Studios option."},
            {"day": 8, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-china-explorer",
        "title": "China Explorer - Beijing & Shanghai",
        "destination": "Beijing",
        "country": "China",
        "category": "International",
        "region": "East Asia",
        "price": 129999,
        "duration_nights": 6,
        "duration_days": 7,
        "image": IMG + "photo-1508804185872-d7badad00f7d?w=1200&q=80",
        "rating": 4.6,
        "reviews_count": 534,
        "popular": False,
        "best_time": "Apr - Oct",
        "description": "Walk the Great Wall, explore the Forbidden City and marvel at Shanghai's dazzling skyline on this grand journey through China's rich history and modernity.",
        "highlights": ["Great Wall of China", "Forbidden City & Tiananmen Square", "Shanghai Bund & skyline", "Yu Garden visit", "High-speed train experience"],
        "inclusions": ["6 nights hotel stay", "Daily breakfast", "High-speed train", "Return economy airfare", "Visa assistance", "Local guide"],
        "tags": ["Culture", "Sightseeing", "History"],
        "itinerary": [
            {"day": 1, "title": "Arrive Beijing", "detail": "Arrival and transfer to hotel."},
            {"day": 2, "title": "Great Wall", "detail": "Excursion to the Great Wall of China."},
            {"day": 3, "title": "Forbidden City", "detail": "Tiananmen Square and Summer Palace."},
            {"day": 4, "title": "To Shanghai", "detail": "High-speed train to Shanghai."},
            {"day": 5, "title": "Shanghai", "detail": "The Bund and Yu Garden."},
            {"day": 6, "title": "Leisure", "detail": "Free day / Disneyland option."},
            {"day": 7, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
    {
        "id": "pkg-abudhabi-extravaganza",
        "title": "Abu Dhabi Extravaganza",
        "destination": "Abu Dhabi",
        "country": "United Arab Emirates",
        "category": "International",
        "region": "Middle East",
        "price": 64999,
        "duration_nights": 4,
        "duration_days": 5,
        "image": IMG + "photo-1512632578888-169bbbc64f33?w=1200&q=80",
        "rating": 4.7,
        "reviews_count": 811,
        "popular": False,
        "best_time": "Oct - Mar",
        "description": "Experience the grandeur of the UAE capital - the breathtaking Sheikh Zayed Grand Mosque, thrilling Ferrari World and the luxurious Emirates Palace.",
        "highlights": ["Sheikh Zayed Grand Mosque", "Ferrari World Abu Dhabi", "Louvre Abu Dhabi", "Yas Island & Corniche", "Desert safari with dinner"],
        "inclusions": ["4 nights hotel stay", "Daily breakfast", "Airport transfers", "Return economy airfare", "Visa assistance", "City tour"],
        "tags": ["Family", "Luxury", "Adventure"],
        "itinerary": [
            {"day": 1, "title": "Arrive Abu Dhabi", "detail": "Arrival and transfer to hotel."},
            {"day": 2, "title": "City Tour", "detail": "Grand Mosque, Corniche and Louvre."},
            {"day": 3, "title": "Yas Island", "detail": "Ferrari World theme park."},
            {"day": 4, "title": "Desert Safari", "detail": "Dune bashing with BBQ dinner."},
            {"day": 5, "title": "Departure", "detail": "Transfer to airport."},
        ],
    },
]

DESTINATIONS = sorted(list({p["destination"] for p in PACKAGES}))
REGIONS = sorted(list({p["region"] for p in PACKAGES}))

# ---------- Forex ----------
FOREX_RATES = [
    {"code": "USD", "name": "US Dollar", "flag": "\U0001F1FA\U0001F1F8", "buy": 83.12, "sell": 85.64, "card_rate": 85.10},
    {"code": "EUR", "name": "Euro", "flag": "\U0001F1EA\U0001F1FA", "buy": 89.45, "sell": 92.30, "card_rate": 91.80},
    {"code": "GBP", "name": "British Pound", "flag": "\U0001F1EC\U0001F1E7", "buy": 104.20, "sell": 108.15, "card_rate": 107.50},
    {"code": "AUD", "name": "Australian Dollar", "flag": "\U0001F1E6\U0001F1FA", "buy": 53.80, "sell": 56.20, "card_rate": 55.70},
    {"code": "AED", "name": "UAE Dirham", "flag": "\U0001F1E6\U0001F1EA", "buy": 22.10, "sell": 23.45, "card_rate": 23.10},
    {"code": "SGD", "name": "Singapore Dollar", "flag": "\U0001F1F8\U0001F1EC", "buy": 61.50, "sell": 63.90, "card_rate": 63.40},
    {"code": "THB", "name": "Thai Baht", "flag": "\U0001F1F9\U0001F1ED", "buy": 2.28, "sell": 2.52, "card_rate": 2.46},
    {"code": "JPY", "name": "Japanese Yen", "flag": "\U0001F1EF\U0001F1F5", "buy": 0.53, "sell": 0.58, "card_rate": 0.57},
    {"code": "CAD", "name": "Canadian Dollar", "flag": "\U0001F1E8\U0001F1E6", "buy": 59.90, "sell": 62.40, "card_rate": 61.90},
    {"code": "CHF", "name": "Swiss Franc", "flag": "\U0001F1E8\U0001F1ED", "buy": 92.30, "sell": 95.60, "card_rate": 95.00},
]

FOREX_PRODUCTS = [
    {"title": "Buy Forex", "desc": "Get foreign currency & forex cards at competitive rates before you fly.", "icon": "buy"},
    {"title": "Student Fees", "desc": "Pay university fees and living expenses abroad with zero hassle.", "icon": "student"},
    {"title": "Sell Forex", "desc": "Sell your leftover foreign currency at attractive buy-back rates.", "icon": "sell"},
    {"title": "Currency Notes", "desc": "Foreign currency notes delivered to your doorstep.", "icon": "notes"},
    {"title": "Send Money", "desc": "Remit money abroad for education, family or medical needs securely.", "icon": "send"},
    {"title": "Forex on WhatsApp", "desc": "Order forex and track your request right from WhatsApp.", "icon": "whatsapp"},
]

FOREX_STATS = [
    {"value": "Zero Markup", "label": "Transparent Rates"},
    {"value": "Doorstep", "label": "Delivery Across India"},
    {"value": "RBI", "label": "Authorised Dealer"},
    {"value": "24\u00d77", "label": "Expert Support"},
]

# Svaagat Cards (Coming Soon)
FOREX_CARDS = [
    {"name": "Borderless Travel Card", "desc": "Load 20+ currencies on one chip-secured card with premium airport services.", "gradient": "from-sky-600 to-blue-900", "tag": "Most Popular"},
    {"name": "Study Buddy Card", "desc": "A zero-markup card designed for students studying abroad.", "gradient": "from-emerald-500 to-teal-800"},
    {"name": "Zero Forex Card", "desc": "Zero cross-currency conversion charges anywhere in the world.", "gradient": "from-fuchsia-500 to-purple-800"},
    {"name": "Enterprise Card", "desc": "A smart, controlled forex solution for corporate & business travel.", "gradient": "from-amber-500 to-orange-700"},
]

CARD_BANNER_FEATURES = [
    {"icon": "badge", "title": "Free ISIC"},
    {"icon": "card", "title": "International 3rd Card"},
    {"icon": "plane", "title": "Airport Lounge Access"},
    {"icon": "shield", "title": "Insurance Coverage"},
]

FOREX_STEPS = [
    {"step": "01", "title": "Select currency & amount", "desc": "Choose your currency and enter the amount you need."},
    {"step": "02", "title": "Add traveller details", "desc": "Share your travel, ID and delivery details."},
    {"step": "03", "title": "Complete payment", "desc": "Pay securely online and get instant confirmation."},
]

FOREX_WHY = [
    {"icon": "shield", "title": "Safe & Secure", "desc": "Bank-grade security on every transaction."},
    {"icon": "trending", "title": "Best Online Rates", "desc": "Competitive, transparent exchange rates."},
    {"icon": "truck", "title": "Doorstep Delivery", "desc": "Currency & cards delivered to your home."},
    {"icon": "badge", "title": "RBI Authorised", "desc": "A fully authorised dealer you can trust."},
]

FOREX_BLOGS = [
    {"title": "A Complete Guide to Forex Cards for Travellers", "category": "Forex Card", "image": IMG + "photo-1554224155-6726b3ff858f?w=600&q=80", "read": "5 min read"},
    {"title": "Studying Abroad? Here's How to Manage Money", "category": "Study Buddy", "image": IMG + "photo-1523240795612-9a054b0db644?w=600&q=80", "read": "6 min read"},
    {"title": "How to Get the Best Currency Exchange Rates", "category": "Currency Notes", "image": IMG + "photo-1580519542036-c47de6196ba5?w=600&q=80", "read": "4 min read"},
    {"title": "Sending Money Abroad: Everything You Need to Know", "category": "Remittance", "image": IMG + "photo-1526304640581-d334cdbbf45e?w=600&q=80", "read": "7 min read"},
]

FOREX_VIDEOS = [
    {"title": "How the Borderless Travel Card Works", "image": IMG + "photo-1512453979798-5ea266f8880c?w=600&q=80"},
    {"title": "Study Abroad Forex Made Simple", "image": IMG + "photo-1523240795612-9a054b0db644?w=600&q=80"},
    {"title": "Doorstep Forex Delivery Explained", "image": IMG + "photo-1554224155-6726b3ff858f?w=600&q=80"},
    {"title": "Best Rates on Foreign Currency", "image": IMG + "photo-1580519542036-c47de6196ba5?w=600&q=80"},
]

FOREX_PARTNERS = ["Visa", "Mastercard", "RuPay", "NPCI", "SWIFT", "RBI Authorised"]

FOREX_FAQS = [
    {"q": "What is a Forex Card and how does it work?", "a": "A Forex Card is a prepaid travel card loaded with foreign currency. It lets you lock in exchange rates, is safer than carrying cash, and is accepted at millions of merchants and ATMs worldwide."},
    {"q": "How do I buy foreign currency from Svaagat Travels?", "a": "Simply select your currency and amount online, share your travel details and complete a secure payment. Your forex is delivered to your doorstep or ready for pickup at a branch."},
    {"q": "What documents are required to purchase forex?", "a": "You typically need a valid passport, confirmed air ticket, visa (where applicable) and a PAN card. Our team guides you through the exact requirements."},
    {"q": "Can I sell my leftover foreign currency after my trip?", "a": "Yes, you can sell unused foreign currency back to us at attractive buy-back rates, either online or at any branch."},
    {"q": "Is there a limit on how much forex I can buy?", "a": "Forex purchase limits are governed by RBI's Liberalised Remittance Scheme (LRS). Our experts will help you stay within the applicable limits."},
]

FOREX_TESTIMONIAL = {"name": "Manmeet Kaur", "location": "Chandigarh", "rating": 5, "text": "I had a wonderful experience with the Svaagat forex team. Getting my study-abroad forex card was extremely quick and easy, with great rates and zero markup. The doorstep delivery was highly convenient. Highly recommend Svaagat Travels for all forex needs!"}

# ---------- FAQs ----------
FAQS = [
    {"q": "How do I book a holiday package with Svaagat Travels?", "a": "You can book online by browsing our holiday packages, selecting your preferred destination and dates, and completing a secure payment. Alternatively, you can visit any of our branches or call our travel experts for assistance."},
    {"q": "What documents do I need for international travel?", "a": "You typically need a valid passport (with at least 6 months validity), applicable visa, confirmed flight tickets, hotel vouchers, and travel insurance. Our team assists with visa documentation for most destinations."},
    {"q": "Does Svaagat Travels provide visa assistance?", "a": "Yes, we provide end-to-end visa assistance for most destinations including documentation guidance, application submission and appointment scheduling wherever applicable."},
    {"q": "Can I customize my holiday package?", "a": "Absolutely! Most of our packages are customizable. You can modify the duration, hotels, add excursions or plan a completely tailor-made itinerary with our destination experts."},
    {"q": "What is a Forex Card and how does it work?", "a": "A Forex Card is a prepaid travel card loaded with foreign currency. It lets you lock in exchange rates, is safer than carrying cash, and is accepted at millions of merchants and ATMs worldwide."},
    {"q": "What is the cancellation and refund policy?", "a": "Cancellation charges vary by package and how far in advance you cancel. Refunds are processed as per the applicable policy within 7-14 business days. Please review the specific terms during booking."},
    {"q": "Is travel insurance included in the package?", "a": "Basic travel insurance is included in most international packages. We recommend comprehensive coverage which can be added during booking for complete peace of mind."},
    {"q": "How early should I book my holiday?", "a": "We recommend booking at least 30-45 days in advance for international trips to secure the best prices on flights and hotels, and to allow sufficient time for visa processing."},
]

# ---------- Offers ----------
OFFERS = [
    {"title": "Flat 15% Off on International Holidays", "desc": "Book your dream international getaway and save big this season.", "tag": "HOLIDAYS", "code": "GOWORLD15", "color": "from-rose-500 to-red-600"},
    {"title": "Zero Forex Markup on Study Abroad Card", "desc": "Special rates for students travelling for education overseas.", "tag": "FOREX", "code": "STUDY0", "color": "from-amber-500 to-orange-600"},
    {"title": "Kashmir & Kerala from Rs. 24,999", "desc": "Explore incredible India with our best-priced domestic packages.", "tag": "DOMESTIC", "code": "INDIA25", "color": "from-emerald-500 to-teal-600"},
    {"title": "Honeymoon Specials - Extra Perks", "desc": "Complimentary candle-light dinner & room upgrades for couples.", "tag": "HONEYMOON", "code": "LOVE2026", "color": "from-fuchsia-500 to-pink-600"},
]

# ---------- Tourism Boards ----------
TOURISM_BOARDS = [
    {"name": "Dubai Tourism", "destination": "Dubai", "image": IMG + "photo-1512453979798-5ea266f8880c?w=600&q=80"},
    {"name": "Tourism Authority of Thailand", "destination": "Thailand", "image": IMG + "photo-1552465011-b4e21bf6e79a?w=600&q=80"},
    {"name": "Singapore Tourism Board", "destination": "Singapore", "image": IMG + "photo-1525625293386-3f8f99389edd?w=600&q=80"},
    {"name": "Switzerland Tourism", "destination": "Switzerland", "image": IMG + "photo-1530122037265-a5f1f91d3b99?w=600&q=80"},
    {"name": "Tourism Malaysia", "destination": "Malaysia", "image": IMG + "photo-1596422846543-75c6fc197f07?w=600&q=80"},
    {"name": "Bali Indonesia", "destination": "Bali", "image": IMG + "photo-1537996194471-e657df975ab4?w=600&q=80"},
]

# ---------- Testimonials ----------
TESTIMONIALS = [
    {"name": "Priya Sharma", "location": "Mumbai", "rating": 5, "text": "Our Bali honeymoon was absolutely magical! Svaagat Travels handled every detail perfectly. The water villa was a dream come true.", "avatar": "PS"},
    {"name": "Rajesh Kumar", "location": "Delhi", "rating": 5, "text": "Booked the Europe tour for my family. The tour manager was fantastic and the Indian meals were a lovely touch. Highly recommended!", "avatar": "RK"},
    {"name": "Ananya Iyer", "location": "Bengaluru", "rating": 4, "text": "Kerala backwaters trip was so relaxing. The houseboat experience was the highlight. Great value for money.", "avatar": "AI"},
    {"name": "Mohammed Faisal", "location": "Hyderabad", "rating": 5, "text": "The Forex card made my Dubai trip hassle-free. No hidden charges and great exchange rates. Will use again!", "avatar": "MF"},
    {"name": "Sneha Patil", "location": "Pune", "rating": 5, "text": "Thailand package exceeded expectations. Coral Island and the shows were amazing. Smooth booking experience online.", "avatar": "SP"},
]

# ---------- Company Stats ----------
STATS = [
    {"value": "Bespoke", "label": "Tailor-made Journeys"},
    {"value": "Handpicked", "label": "Luxury Stays Worldwide"},
    {"value": "Concierge", "label": "24\u00d77 Personal Travel Desk"},
    {"value": "Seamless", "label": "Flights \u00b7 Stays \u00b7 Forex"},
]

WHY_US = [
    {"title": "Handcrafted Luxury", "desc": "Every journey is tailor-made around your tastes, pace and passions.", "icon": "shield-check"},
    {"title": "Expert Tour Managers", "desc": "Dedicated managers accompany group tours for a seamless journey.", "icon": "users"},
    {"title": "Best Price Guarantee", "desc": "Competitive prices with exclusive deals and easy EMI options.", "icon": "badge-indian-rupee"},
    {"title": "24x7 Assistance", "desc": "Round-the-clock support before, during and after your trip.", "icon": "headphones"},
    {"title": "End-to-End Service", "desc": "Flights, hotels, visa, forex & insurance - all under one roof.", "icon": "package"},
    {"title": "Personalised Itineraries", "desc": "Tailor-made holidays crafted around your preferences.", "icon": "map"},
]

# ---------- Flights (dummy) ----------
AIRPORTS = [
    {"code": "BOM", "city": "Mumbai", "name": "Chhatrapati Shivaji Intl"},
    {"code": "DEL", "city": "New Delhi", "name": "Indira Gandhi Intl"},
    {"code": "BLR", "city": "Bengaluru", "name": "Kempegowda Intl"},
    {"code": "MAA", "city": "Chennai", "name": "Chennai Intl"},
    {"code": "HYD", "city": "Hyderabad", "name": "Rajiv Gandhi Intl"},
    {"code": "CCU", "city": "Kolkata", "name": "Netaji Subhas Chandra Bose"},
    {"code": "GOI", "city": "Goa", "name": "Dabolim Airport"},
    {"code": "DXB", "city": "Dubai", "name": "Dubai Intl"},
    {"code": "SIN", "city": "Singapore", "name": "Changi Airport"},
    {"code": "BKK", "city": "Bangkok", "name": "Suvarnabhumi Airport"},
    {"code": "LHR", "city": "London", "name": "Heathrow Airport"},
    {"code": "CDG", "city": "Paris", "name": "Charles de Gaulle"},
]

AIRLINES = [
    {"name": "IndiGo", "code": "6E"},
    {"name": "Air India", "code": "AI"},
    {"name": "Vistara", "code": "UK"},
    {"name": "SpiceJet", "code": "SG"},
    {"name": "Emirates", "code": "EK"},
    {"name": "Singapore Airlines", "code": "SQ"},
]

# ---------- Trending Destinations (circular cards) ----------
TRENDING_DESTINATIONS = [
    {"name": "Europe", "query": "Paris", "image": IMG + "photo-1502602898657-3e91760cbb34?w=500&q=80"},
    {"name": "Australia", "query": "Sydney", "image": IMG + "photo-1506973035872-a4ec16b8e8d9?w=500&q=80"},
    {"name": "Japan", "query": "Tokyo", "image": IMG + "photo-1493976040374-85c8e12f0c0e?w=500&q=80"},
    {"name": "Vietnam", "query": "Hanoi", "image": IMG + "photo-1528127269322-539801943592?w=500&q=80"},
    {"name": "China", "query": "Beijing", "image": IMG + "photo-1508804185872-d7badad00f7d?w=500&q=80"},
    {"name": "Abu Dhabi", "query": "Abu Dhabi", "image": IMG + "photo-1512632578888-169bbbc64f33?w=500&q=80"},
    {"name": "Thailand", "query": "Bangkok", "image": IMG + "photo-1552465011-b4e21bf6e79a?w=500&q=80"},
    {"name": "Dubai", "query": "Dubai", "image": IMG + "photo-1512453979798-5ea266f8880c?w=500&q=80"},
]

# ---------- Hero carousel slides ----------
HERO_SLIDES = [
    {"title": "Singapore", "subtitle": "The City Where Moments Become Memories", "cta": "Explore Packages", "query": "Singapore", "image": IMG + "photo-1525625293386-3f8f99389edd?w=1920&q=80"},
    {"title": "Dubai", "subtitle": "Where Luxury Meets Arabian Adventure", "cta": "Explore Packages", "query": "Dubai", "image": IMG + "photo-1512453979798-5ea266f8880c?w=1920&q=80"},
    {"title": "Bali", "subtitle": "Your Island of Gods Awaits", "cta": "Explore Packages", "query": "Bali", "image": IMG + "photo-1537996194471-e657df975ab4?w=1920&q=80"},
    {"title": "Maldives", "subtitle": "Paradise Found, Over Turquoise Waters", "cta": "Explore Packages", "query": "Maldives", "image": IMG + "photo-1514282401047-d79a71a590e8?w=1920&q=80"},
]

# ---------- Top Flight Routes ----------
TOP_FLIGHT_ROUTES = [
    {"from": "Delhi", "to": "Mumbai", "from_code": "DEL", "to_code": "BOM", "airline": "IndiGo", "price": 4499, "type": "Domestic"},
    {"from": "Mumbai", "to": "Dubai", "from_code": "BOM", "to_code": "DXB", "airline": "Emirates", "price": 18999, "type": "International"},
    {"from": "Bengaluru", "to": "Singapore", "from_code": "BLR", "to_code": "SIN", "airline": "Singapore Airlines", "price": 24499, "type": "International"},
    {"from": "Chennai", "to": "Bangkok", "from_code": "MAA", "to_code": "BKK", "airline": "Air India", "price": 16999, "type": "International"},
    {"from": "Kolkata", "to": "Delhi", "from_code": "CCU", "to_code": "DEL", "airline": "Vistara", "price": 5299, "type": "Domestic"},
    {"from": "Delhi", "to": "London", "from_code": "DEL", "to_code": "LHR", "airline": "Air India", "price": 48999, "type": "International"},
    {"from": "Mumbai", "to": "Goa", "from_code": "BOM", "to_code": "GOI", "airline": "IndiGo", "price": 3299, "type": "Domestic"},
    {"from": "Hyderabad", "to": "Paris", "from_code": "HYD", "to_code": "CDG", "airline": "Emirates", "price": 52499, "type": "International"},
    {"from": "Bengaluru", "to": "Chennai", "from_code": "BLR", "to_code": "MAA", "airline": "SpiceJet", "price": 2799, "type": "Domestic"},
]

# ---------- Explore Hotel Stays ----------
HOTEL_STAYS = [
    {"city": "Agra", "hotels": "120+ Hotels", "query": "Srinagar", "image": IMG + "photo-1564507592333-c60657eea523?w=600&q=80"},
    {"city": "Jaipur", "hotels": "95+ Hotels", "query": "Goa", "image": IMG + "photo-1477587458883-47145ed94245?w=600&q=80"},
    {"city": "Goa", "hotels": "210+ Hotels", "query": "Goa", "image": IMG + "photo-1512343879784-a960bf40e7f2?w=600&q=80"},
    {"city": "Dubai", "hotels": "300+ Hotels", "query": "Dubai", "image": IMG + "photo-1512453979798-5ea266f8880c?w=600&q=80"},
    {"city": "Bangkok", "hotels": "180+ Hotels", "query": "Bangkok", "image": IMG + "photo-1552465011-b4e21bf6e79a?w=600&q=80"},
]

# ---------- Service tags (SEO pills) ----------
SERVICE_TAGS = [
    "International Holiday Packages", "India Holiday Packages", "Honeymoon Packages", "Family Tour Packages",
    "Group Tour Packages", "Cruise Packages", "Weekend Getaways", "Adventure Holidays", "Beach Holidays",
    "Pilgrimage Tours", "Visa Services", "Forex Card", "Foreign Currency", "Travel Insurance",
    "Dubai Tour Packages", "Thailand Tour Packages", "Bali Tour Packages", "Maldives Packages",
    "Singapore Packages", "Europe Tour Packages", "Vietnam Packages", "Kashmir Packages",
    "Kerala Packages", "Goa Packages", "Andaman Packages", "Ladakh Packages", "Rajasthan Tours",
    "Domestic Flights", "International Flights", "Cheap Flights", "Corporate Travel",
    "Student Forex Card", "Money Transfer Abroad", "Multi-Currency Card", "Gift Cards", "Loyalty Rewards",
]

# ---------- Why choose feature callouts ----------
WHY_FEATURES = [
    {"title": "Customized Holiday Packages", "desc": "Tailor-made itineraries designed around you."},
    {"title": "Wide Range of Holidays", "desc": "Curated tours across India & the world."},
    {"title": "Seamless Booking", "desc": "Book flights, hotels, forex in a few clicks."},
    {"title": "Expert Assistance 24x7", "desc": "Dedicated travel experts, always available."},
]
